export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST'
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS'
export const POST_CREATE_FAIL = 'POST_CREATE_FAIL'
export const POST_CREATE_RESET = 'POST_CREATE_RESET'


export const POST_DETAILS_REQUEST = 'POST_DETAILS_REQUEST'
export const POST_DETAILS_SUCCESS = 'POST_DETAILS_SUCCESS'
export const POST_DETAILS_FAIL = 'POST_DETAILS_FAIL'
export const POST_DETAILS_RESET = 'POST_DETAILS_RESET'

export const POST_LIST_REQUEST = 'POST_LIST_REQUEST'
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS'
export const POST_LIST_FAIL = 'POST_LIST_FAIL'
export const POST_LIST_RESET = 'POST_LIST_RESET'


export const POST_MYLIST_REQUEST = 'POST_MYLIST_REQUEST'
export const POST_MYLIST_SUCCESS = 'POST_MYLIST_SUCCESS'
export const POST_MYLIST_FAIL = 'POST_MYLIST_FAIL'
export const POST_MYLIST_RESET = 'POST_MYLIST_RESET'


export const POST_DELETE_REQUEST = 'POST_DELETE_REQUEST'
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS'
export const POST_DELETE_FAIL = 'POST_DELETE_FAIL'


export const POST_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const POST_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const POST_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const POST_UPDATE_RESET = 'USER_UPDATE_RESET'
