export const COMMENTS_CREATE_REQUEST = 'COMMENTS_CREATE_REQUEST'
export const COMMENTS_CREATE_SUCCESS = 'COMMENTS_CREATE_SUCCESS'
export const COMMENTS_CREATE_FAIL = 'COMMENTS_CREATE_FAIL'
export const COMMENTS_CREATE_RESET = 'COMMENTS_CREATE_RESET'


export const COMMENTS_DETAILS_REQUEST = 'COMMENTS_DETAILS_REQUEST'
export const COMMENTS_DETAILS_SUCCESS = 'COMMENTS_DETAILS_SUCCESS'
export const COMMENTS_DETAILS_FAIL = 'COMMENTS_DETAILS_FAIL'
export const COMMENTS_DETAILS_RESET = 'COMMENTS_DETAILS_RESET'

export const COMMENTS_LIST_REQUEST = 'POST_LIST_REQUEST'
export const COMMENTS_LIST_SUCCESS = 'POST_LIST_SUCCESS'
export const COMMENTS_LIST_FAIL = 'POST_LIST_FAIL'
export const COMMENTS_LIST_RESET = 'POST_LIST_RESET'
