export const FBSTATISTICS_DETAILS_REQUEST = 'FBSTATISTICS_DETAILS_REQUEST'
export const FBSTATISTICS_DETAILS_SUCCESS = 'FBSTATISTICS_DETAILS_SUCCESS'
export const FBSTATISTICS_DETAILS_FAIL = 'FBSTATISTICS_DETAILS_FAIL'
export const FBSTATISTICS_DETAILS_RESET = 'FBSTATISTICS_DETAILS_RESET'

export const FBRATINGS_DETAILS_REQUEST = 'FBRATINGS_DETAILS_REQUEST'
export const FBRATINGS_DETAILS_SUCCESS = 'FBRATINGS_DETAILS_SUCCESS'
export const FBRATINGS_DETAILS_FAIL = 'FBRATINGS_DETAILS_FAIL'
export const FBRATINGS_DETAILS_RESET = 'FBRATINGS_DETAILS_RESET'
