export const GSSTATISTICS_DETAILS_REQUEST = 'GSSTATISTICS_DETAILS_REQUEST'
export const GSSTATISTICS_DETAILS_SUCCESS = 'GSSTATISTICS_DETAILS_SUCCESS'
export const GSSTATISTICS_DETAILS_FAIL = 'GSSTATISTICS_DETAILS_FAIL'
export const GSSTATISTICS_DETAILS_RESET = 'GSSTATISTICS_DETAILS_RESET'

export const GSRATINGS_DETAILS_REQUEST = 'GSRATINGS_DETAILS_REQUEST'
export const GSRATINGS_DETAILS_SUCCESS = 'GSRATINGS_DETAILS_SUCCESS'
export const GSRATINGS_DETAILS_FAIL = 'GSRATINGS_DETAILS_FAIL'
export const GSRATINGS_DETAILS_RESET = 'GSRATINGS_DETAILS_RESET'




