export const WINNER_LIST_REQUEST = 'WINNER_LIST_REQUEST'
export const WINNER_LIST_SUCCESS = 'WINNER_LIST_SUCCESS'
export const WINNER_LIST_FAIL = 'WINNER_LIST_FAIL'
export const WINNER_LIST_RESET = 'WINNER_LIST_RESET'
