export const PRIZE_CREATE_REQUEST = 'PRIZE_CREATE_REQUEST'
export const PRIZE_CREATE_SUCCESS = 'PRIZE_CREATE_SUCCESS'
export const PRIZE_CREATE_FAIL = 'PRIZE_CREATE_FAIL'
export const PRIZE_CREATE_RESET = 'PRIZE_CREATE_RESET'

export const PRIZE_LIST_REQUEST = 'PRIZE_LIST_REQUEST'
export const PRIZE_LIST_SUCCESS = 'PRIZE_LIST_SUCCESS'
export const PRIZE_LIST_FAIL = 'PRIZE_LIST_FAIL'
export const PRIZE_LIST_RESET = 'PRIZE_LIST_RESET'
