export const CATEGORY_CREATE_REQUEST = 'CATEGORY_CREATE_REQUEST'
export const CATEGORY_CREATE_SUCCESS = 'CATEGORY_CREATE_SUCCESS'
export const CATEGORY_CREATE_FAIL = 'CATEGORY_CREATE_FAIL'
export const CATEGORY_CREATE_RESET = 'CATEGORY_CREATE_RESET'

export const CATEGORY_LIST_CREATE_REQUEST = 'CATEGORY_LIST_CREATE_REQUEST'
export const CATEGORY_LIST_CREATE_SUCCESS = 'CATEGORY_CREATE_LIST_SUCCESS'
export const CATEGORY_LIST_CREATE_FAIL = 'CATEGORY_CREATE_LIST_FAIL'
export const CATEGORY_LIST_CREATE_RESET = 'CATEGORY_CREATE_LIST_RESET'

export const CATEGORY_DELETE_REQUEST = 'CATEGORY_DELETE_REQUEST'
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS'
export const CATEGORY_DELETE_FAIL = 'CATEGORY_DELETE_FAIL'


export const QUESTION_LIST_CREATE_REQUEST = 'QUESTION_LIST_CREATE_REQUEST'
export const QUESTION_LIST_CREATE_SUCCESS = 'QUESTION_CREATE_LIST_SUCCESS'
export const QUESTION_LIST_CREATE_FAIL = 'QUESTION_CREATE_LIST_FAIL'
export const QUESTION_LIST_CREATE_RESET = 'QUESTION_CREATE_LIST_RESET'

export const QUESTION_DELETE_REQUEST = 'QUESTION_DELETE_REQUEST'
export const QUESTION_DELETE_SUCCESS = 'QUESTION_DELETE_SUCCESS'
export const QUESTION_DELETE_FAIL = 'QUESTION_DELETE_FAIL'
export const QUESTION_DELETE_RESET = 'QUESTION_DELETE_RESET'

export const QUESTION_CREATE_REQUEST = 'QUESTION_CREATE_REQUEST'
export const QUESTION_CREATE_SUCCESS = 'QUESTION_CREATE_SUCCESS'
export const QUESTION_CREATE_FAIL = 'QUESTION_CREATE_FAIL'
export const QUESTION_CREATE_RESET = 'QUESTION_CREATE_RESET'

export const ANSWER_DELETE_REQUEST = 'ANSWER_DELETE_REQUEST'
export const ANSWER_DELETE_SUCCESS = 'ANSWER_DELETE_SUCCESS'
export const ANSWER_DELETE_FAIL = 'ANSWER_DELETE_FAIL'
export const ANSWER_DELETE_RESET = 'ANSWER_DELETE_RESET'

export const ANSWER_DETAIL_REQUEST = 'ANSWER_DETAIL_REQUEST'
export const ANSWER_DETAIL_SUCCESS = 'ANSWER_DETAIL_SUCCESS'
export const ANSWER_DETAIL_FAIL = 'ANSWER_DETAIL_FAIL'
export const ANSWER_DETAIL_RESET = 'ANSWER_DETAIL_RESET'

export const ANSWER_CREATE_REQUEST = 'ANSWER_CREATE_REQUEST'
export const ANSWER_CREATE_SUCCESS = 'ANSWER_CREATE_SUCCESS'
export const ANSWER_CREATE_FAIL = 'ANSWER_CREATE_FAIL'
export const ANSWER_CREATE_RESET = 'ANSWER_CREATE_RESET'
