# Generated by Django 3.1.4 on 2023-01-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20230102_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_name', models.TextField(max_length=500)),
                ('prize_content', models.TextField(max_length=500)),
                ('prize_team', models.TextField(max_length=500)),
                ('winner_ladder', models.TextField(max_length=500)),
            ],
        ),
    ]
